select * from MM_Paises
select * from MM_DadosGeograficos
delete from MM_Paises
insert into MM_Paises values ('Russia', 'Moscow')
update MM_Paises set nome = 'Colombia' where Id = 2

INSERT INTO MM_Paises ()
VALUES
('Afghanistan','Kabul'),
('American Samoa','Pago Pago'),
('Akrotiri Sovereign Base Area', NULL),
('Albania','Tirana'),
('Aland','Mariehamn'),
('Algeria','Algiers'),
('Angola','Luanda'),
('Andorra','Andorra La Vella'),
('Argentina', 'Buenos Aires'),
('Armenia', 'Yerevan'),
('Antigua and Barbuda', 'Saint Johns'),
('Australia','Canberra'),
('Austria','Vienna'),
('Aruba','Oranjestade'),
('Ashmore and Cartier Islands',NULL),
('Azerbaijan','Baku'),
('Anguilla','Vale'),
('Antarctica',NULL),
('The Bahamas','Nassau'),
('Bangladesh','Dhaka'),
('Bahrain', 'Manama'),
('Barbados','Bridgetown'),
('Baykonur Cosmodrome', 'Kyzylorda')
('Belarus','Minsk'),
('Belgium','Brussels'),
('Belize','Belmopan'),
('Belarus','Minsk'),
('Benin','Porto-Novo'),
('Bhutan','Thimphu'),
('Bermuda','Hamilton'),
('Bolivia','La Paz'),
('Bosnia and Herzegovina','Sarajevo'),
('Botswana','Gaborone'),
('British Indian Ocean Territory',NULL),
('British Virgin Islands','Road Town'),
('Brunei','Bandar Seri Begawan'),
('Bulgaria','Sofia'),
('Burkina Faso','Kyzylorda'),
('Burundi','Gitega'),
('Cambodia','Phnom Penh'),
('Cameroon','Yaounde'),
('Canada','Ottawa'),
('Cape Verde','Praia'),
('Cayman Islands','George Town'),
('Central African Republic','Bangui'),
('Chad','Djamena'),
('Chile','Santiago'),
('China','Pequim'),
('Clipperton Island', NULL),
('Comoros','Moroni'),
('Cook Islands','Avarua'),
('Coral Sea Islands',NULL),
('Costa Rica','San José'),
('Croatia','Zagrebe'),
('Cuba','Havana'),
('Cyprus','Nicósia'),
('Cyprus No Mans Area', NULL)
('Czech Republic','Praga'),
('Democratic Republic of the Congo','Brazzavile'),
('Denmark','Copenhagen'),
('Dhekelia Soverign Base Area',NULL),
('Djibouti','Djibuti'),
('Dominica','Roseau'),
('Dominican Republic','Santo Dominica'),
('East Timor','Díli'),
('Ecuador','Quito'),
('Egypt','Kairo'),
('El Salvador','São Salvador'),
('Equatorial Guinea','Malabo'),
('Eritrea','Asmara'),
('Estonia','Talín'),
('Ethiopia','Addis Ababa'),
('Falkland Islands','Stanley'),
('Faroe Islands','Tórshavn'),
('Federated States of Micronesia','Palikiro'),
('Fiji','Suva'),
('Finland','Helsinque'),
('France','Paris'),
('French Polynesia','Papete'),
('French Southern and Antarctic Lands','Saint-Pierre'),
('Gabon','Libreville'),
('Gambia','Fajul'),
('Georgia','Tiblissi'),
('Gaza Strip', NULL),
('Germany','Berlim'),
('Ghana','Acra'),
('Gibraltar','Gibraltar'),
('Greece','Athens'),
('Greenland','Nuuk'),
('Grenada','Saint Georges'),
('Guam','Hagåtña'),
('Guatemala','Guatemala City'),
('Guernsey','Saint Peter Port'),
('Guinea','Conakri'),
('Guinea Bissau','Bissau'),
('Guyana','Georgetown'),
('Haiti','Porto Príncipe'),
('Heard Island and McDonald Islands',NULL),
('Honduras','Tegucipalga'),
('Hong Kong S.A.R..','Hong Kong'),
('Hungary','Budapeste'),
('Iceland','Reykjavik'),
('India','New Delhi'),
('Indian Ocean Territories',NULL),
('Indonesia','Jacarta'),
('Iran','Tehran'),
('Iraq','Bagdá'),
('Ireland','Dublin'),
('Isle of Man','Douglas'),
('Israel','Jerusalem'),
('Italy','Rome'),
('Ivory Coast','Yamussucro'),
('Jamaica','Kingston'),
('Japan','Tokyo'),
('Jersey','Saint Heiler'),
('Jordan','Amã'),
('Kazakhstan','Astana'),
('Kenya','Nairobi'),
('Kiribati','Tarawa'),
('Korea No Mans Area',NULL),
('Kosovo','Pristina'),
('Kuwait','Kuwait'),
('Kyrgyzstan','Bishkek'),
('Laos','Vienciana'),
('Latvia','Riga'),
('Lebanon','Beirute'),
('Lesotho','Maseru'),
---------------------------------------
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macau S.A.R.'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro',),
('Montserrat',),
('Morocco',),
('Mozambique',),
('Myanmar',),
('Namibia',),
('Nauru',),
('Nepal',),
('Netherlands',),
('New Caledonia',),
('New Zealand',),
('Nicaragua',),
('Niger',),
('Nigeria',),
('Niue',),
('Norfolk Island',),
('North Korea',),
('Northern Cyprus'),
('Northern Mariana Islands',),
('Norway',),
('Oman',),
('Pakistan',),
('Palau',),
('Panama',),
('Papua New Guinea',),
('Paraguay',),
('Peru',),
('Philippines',),
('Pitcairn Islands',),
('Poland',),
('Portugal',),
('Puerto Rico',),
('Qatar',),
('Republic of Serbia',),
('Republic of the Congo',),
('S. Sudan.',),
('Romania',),
('Rwanda',),
('Saint Barthelemy',),
('Saint Helena',),
('Saint Kitts and Nevis',),
('Saint Lucia',),
('Saint Martin',),
('Saint Pierre and Miquelon',),
('Saint Vincent and the Grenadines',),
('Samoa',),
('San Marino',),
('Sao Tome and Principe',),
('Saudi Arabia',),
('Senegal',),
('Seychelles',),
('Siachen Glacier', ),
('Sierra Leone',),
('Singapore',),
('Sint Maarten',),
('Slovakia',),
('Slovenia',),
('Solomon Islands',),
('Somalia',),
('Somaliland', ),
('South Africa',),
('South Georgia and the Islands',),
('South Korea',),
('Spain',),
('Spratly Is..', ),
('Sri Lanka',),
('Sudan',),
('Suriname',),
('Swaziland',),
('Sweden',),
('Switzerland',),
('Syria',),
('Taiwan',),
('Tajikistan',),
('Thailand',),
('Togo',),
('Tonga',),
('Trinidad and Tobago',),
('Tunisia',),
('Turkey',),
('Turkmenistan',),
('Turks and Caicos Islands',),
('Tuvalu',),
('US Naval Base Guantanamo Bay', ),
('United States Minor Outlying Islands.',),
('United States Virgin Islands',),
('United Republic of Tanzania', ),
('Uganda',),
('Ukraine',),
('United Arab Emirates',),
('United Kingdom',),
('Uruguay',),
('Uzbekistan',),
('Vanuatu',),
('Vatican',),
('Venezuela',),
('Vietnam',),
('Wallis and Futuna',),
('West Bank', ),
('Western Sahara',),
('Yemen',),
('Zambia',),
('Zimbabwe',);