select * from MM_Paises
select * from MM_DadosGeograficos
delete from MM_Paises
insert into MM_Paises values ('Russia', 'Moscow')
update MM_Paises set nome = 'Colombia' where Id = 2

INSERT INTO MM_Paises ()
VALUES
('Afghanistan','Kabul'),
('American Samoa','Pago Pago'),
('Akrotiri Sovereign Base Area', NULL),
('Albania','Tirana'),
('Aland','Mariehamn'),
('Algeria','Algiers'),
('Angola','Luanda'),
('Andorra','Andorra La Vella'),
('Argentina', 'Buenos Aires'),
('Armenia', 'Yerevan'),
('Antigua and Barbuda', 'Saint Johns'),
('Australia','Canberra'),
('Austria','Vienna'),
('Aruba','Oranjestade'),
('Ashford and Cartier Island',NULL),
('Azerbaijan','Baku'),
('Anguilla','Vale'),
('Antartica',NULL),
('The Bahamas','Nassau'),
('Bangladesh','Dhaka'),
('Bahrain', 'Manama'),
('Barbados','Bridgetown'),
('Belarus','Minsk'),
('Belgium','Brussels'),
('Belize','Belmopan'),
('Belarus','Minsk'),
('Benin','Porto-Novo'),
('Bhutan','Thimphu'),
('Bermuda','Hamilton'),
('Bolivia','La Paz'),
('Bosnia and Herzegovina','Sarajevo'),
('Botswana','Gaborone'),
('Brazil','Brasília'),
('British Indian Ocean Territory',NULL),
('British Virgin Islands','Road Town'),
('Brunei','Bandar Seri Begawan'),
('Bulgaria','Sofia'),
('Burkina Faso','Kyzylorda'),
('Burundi','Gitega'),
('Cambodia','Phnom Penh'),
('Cameroon','Yaounde'),
('Canada','Ottawa'),
('Cape Verde','Praia'),
('Cayman Islands','George Town'),
('Central African Republic','Bangui'),
('Chad','Djamena'),
('Chile','Santiago'),
('China','Pequim'),
('Clippertown Island', NULL),
('Cocos [Keeling] Islands','West Island'),
('Colombia','Bogota'),
('Comoros','Moroni'),
('Cook Islands','Avarua'),
('Coral Sea Islands',NULL),
('Costa Rica','San José'),
('Croatia','Zagrebe'),
('Cuba','Havana'),
('Cyprus','Nicósia'),
('Czech Republic','Praga'),
('Democratic Republic of the Congo','Brazzavile'),
('Denmark','Copenhagen'),
('Dhkelia Soverign Base Area',NULL),
('Djibouti','Djibuti'),
('Dominica','Roseau'),
('Dominican Republic','Santo Dominica'),
('East Timor','Díli'),
('Ecuador','Quito'),
('Egypt','Kairo'),
('El Salvador','São Salvador'),
('Equatorial Guinea','Malabo'),
('Eritrea','Asmara'),
('Estonia','Talín'),
('Ethiopia','Addis Ababa'),
('Falkland Islands','Stanley'),
('Faroe Islands','Tórshavn'),
('Federated States of Micronesia','Palikiro'),
('Fiji','Suva'),
('Finland','Helsinque'),
('France','Paris'),
('French Guiana','Caiena'),
('French Polynesia','Papete'),
('French Southern Territories','Saint-Pierre'),
('Gabon','Libreville'),
('Gambia','Fajul'),
('Georgia','Tiblissi'),
('Gaza Strip', NULL),
('Germany','Berlim'),
('Ghana','Acra'),
('Gibraltar','Gibraltar'),
('Greece','Athens'),
('Greenland','Nuuk'),
('Grenada','Saint Georges'),
('Guam','Hagåtña'),
('Guatemala','Guatemala City'),
('Guernsey','Saint Peter Port'),
('Guinea','Conakri'),
('Guinea-Bissau','Bissau'),
('Guyana','Georgetown'),
('Haiti','Porto Príncipe'),
('Heard Island and McDonald Islands',NULL),
('Honduras','Tegucipalga'),
('Hong Kong','Hong Kong'),
('Hungary','Budapeste'),
('Iceland','Reykjavik'),
('India','New Delhi'),
('Indian Ocean Territories',NULL),
('Indonesia','Jacarta'),
('Iran','Tehran'),
('Iraq','Bagdá'),
('Ireland','Dublin'),
('Isle of Man','Douglas'),
('Israel','Jerusalem'),
('Italy','Rome'),
('Ivory Coast','Yamussucro'),
('Jamaica','Kingston'),
('Japan','Tokyo'),
('Jersey','Saint Heiler'),
('Jordan','Amã'),
('Kazakhstan','Astana'),
('Kenya','Nairobi'),
('Kiribati','Tarawa'),
('Kora No Mans Area',NULL),
('Kosovo','Pristina'),
('Kuwait','Kuwait'),
('Kyrgyzstan','Bishkek'),
('Laos','Vienciana'),
('Latvia','Riga'),
('Lebanon','Beirute'),
('Lesotho','Maseru'),
---------------------------------------
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macao'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Martinique'),
('Mauritania'),
('Mauritius'),
('Mayotte'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('MNE','Montenegro','ME'),
('MSR','Montserrat','MS'),
('MAR','Morocco','MA'),
('MOZ','Mozambique','MZ'),
('MMR','Myanmar [Burma]','MM'),
('NAM','Namibia','NA'),
('NRU','Nauru','NR'),
('NPL','Nepal','NP'),
('NLD','Netherlands','NL'),
('NCL','New Caledonia','NC'),
('NZL','New Zealand','NZ'),
('NIC','Nicaragua','NI'),
('NER','Niger','NE'),
('NGA','Nigeria','NG'),
('NIU','Niue','NU'),
('NFK','Norfolk Island','NF'),
('PRK','North Korea','KP'),
('MNP','Northern Mariana Islands','MP'),
('NOR','Norway','NO'),
('OMN','Oman','OM'),
('PAK','Pakistan','PK'),
('PLW','Palau','PW'),
('PSE','Palestine','PS'),
('PAN','Panama','PA'),
('PNG','Papua New Guinea','PG'),
('PRY','Paraguay','PY'),
('PER','Peru','PE'),
('PHL','Philippines','PH'),
('PCN','Pitcairn Islands','PN'),
('POL','Poland','PL'),
('PRT','Portugal','PT'),
('PRI','Puerto Rico','PR'),
('QAT','Qatar','QA'),
('COG','Republic of the Congo','CG'),
('REU','R�union','RE'),
('ROU','Romania','RO'),
('RUS','Russia','RU'),
('RWA','Rwanda','RW'),
('BLM','Saint Barth�lemy','BL'),
('SHN','Saint Helena','SH'),
('KNA','Saint Kitts and Nevis','KN'),
('LCA','Saint Lucia','LC'),
('MAF','Saint Martin','MF'),
('SPM','Saint Pierre and Miquelon','PM'),
('VCT','Saint Vincent and the Grenadines','VC'),
('WSM','Samoa','WS'),
('SMR','San Marino','SM'),
('STP','S�o Tom� and Pr�ncipe','ST'),
('SAU','Saudi Arabia','SA'),
('SEN','Senegal','SN'),
('SRB','Serbia','RS'),
('SYC','Seychelles','SC'),
('SLE','Sierra Leone','SL'),
('SGP','Singapore','SG'),
('SXM','Sint Maarten','SX'),
('SVK','Slovakia','SK'),
('SVN','Slovenia','SI'),
('SLB','Solomon Islands','SB'),
('SOM','Somalia','SO'),
('ZAF','South Africa','ZA'),
('SGS','South Georgia and the South Sandwich Islands','GS'),
('KOR','South Korea','KR'),
('SSD','South Sudan','SS'),
('ESP','Spain','ES'),
('LKA','Sri Lanka','LK'),
('SDN','Sudan','SD'),
('SUR','Suriname','SR'),
('SJM','Svalbard and Jan Mayen','SJ'),
('SWZ','Swaziland','SZ'),
('SWE','Sweden','SE'),
('CHE','Switzerland','CH'),
('SYR','Syria','SY'),
('TWN','Taiwan','TW'),
('TJK','Tajikistan','TJ'),
('TZA','Tanzania','TZ'),
('THA','Thailand','TH'),
('TGO','Togo','TG'),
('TKL','Tokelau','TK'),
('TON','Tonga','TO'),
('TTO','Trinidad and Tobago','TT'),
('TUN','Tunisia','TN'),
('TUR','Turkey','TR'),
('TKM','Turkmenistan','TM'),
('TCA','Turks and Caicos Islands','TC'),
('TUV','Tuvalu','TV'),
('UMI','U.S. Minor Outlying Islands','UM'),
('VIR','U.S. Virgin Islands','VI'),
('UGA','Uganda','UG'),
('UKR','Ukraine','UA'),
('ARE','United Arab Emirates','AE'),
('GBR','United Kingdom','GB'),
('USA','United States','US'),
('URY','Uruguay','UY'),
('UZB','Uzbekistan','UZ'),
('VUT','Vanuatu','VU'),
('VAT','Vatican City','VA'),
('VEN','Venezuela','VE'),
('VNM','Vietnam','VN'),
('WLF','Wallis and Futuna','WF'),
('ESH','Western Sahara','EH'),
('YEM','Yemen','YE'),
('ZMB','Zambia','ZM'),
('ZWE','Zimbabwe','ZW');